### ISSUE TITLE
Year returns NaN

### ISSUE THREAD

**Issue by tkozybski** [lakafior/lubimyczytac-abs#5]
For https://lubimyczytac.pl/ksiazka/4846911/przebudzenie-lewiatana it returns NaN instead of a number. It would be better if it returned nothing if it can't parse a year.

**Comment by lakafior** [comment]
Hi sorry for the late reply, I've had Christmas break from work. It should return empty value instead of NaN if no year is given:
The year is given:
![obraz](https://github.com/user-attachments/assets/2b28dbb1-4beb-4485-9921-8e178121fde3)
No year is given:
![obraz](https://github.com/user-attachments/assets/31cd96fb-f978-4468-a851-d9a06ad343c4)
